<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="DESKTOP-U8GE9MR" name="Practise_pck.TS_01" tests="5" failures="1" timestamp="2023-03-29T10:26:40 IST" time="0.058" errors="0">
  <testcase name="method1" time="0.000" classname="Practise_pck.TS_01">
    <skipped/>
  </testcase> <!-- method1 -->
  <system-out>
    <![CDATA[method01]]>
  </system-out>
  <testcase name="method2" time="0.000" classname="Practise_pck.TS_01"/>
  <system-out>
    <![CDATA[method02]]>
  </system-out>
  <testcase name="method1" time="0.058" classname="Practise_pck.TS_01">
    <skipped/>
  </testcase> <!-- method1 -->
  <system-out>
    <![CDATA[method01]]>
  </system-out>
  <testcase name="method1" time="0.000" classname="Practise_pck.TS_01">
    <skipped/>
  </testcase> <!-- method1 -->
  <system-out>
    <![CDATA[method01]]>
  </system-out>
  <testcase name="method1" time="0.000" classname="Practise_pck.TS_01">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at Practise_pck.TS_01.method1(TS_01.java:14)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- method1 -->
  <system-out>
    <![CDATA[method01]]>
  </system-out>
</testsuite> <!-- Practise_pck.TS_01 -->
